- name: add add-apt-repostory
  apt: pkg=software-properties-common state=present update_cache=yes
    
- name: add add-apt-repostory
  apt: pkg=python-software-properties state=present update_cache=yes
  when: ansible_distribution_release == "precise"

- name: add webupd8 ppa
  apt_repository: repo='ppa:webupd8team/java'

- name: update and upgrade apt packages
  apt: >
    upgrade=yes
    update_cache=yes
    cache_valid_time=3600

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: install java8
  shell: apt-get install -y oracle-java8-installer ca-certificates
