- name: Deploy checkBox.io after hook

  hosts: checkboxDeploy

  tasks:

    - name: Copy the latest code from local repo.
      synchronize:
        src: /home/vagrant/www/
        dest: /home/vagrant/checkbox.io/
        recursive: yes

# Configure nginx
    - name: Update nginx.conf
      copy: remote_src=True src=/home/vagrant/checkbox.io/local-conf/nginx.conf dest=/etc/nginx/nginx.conf
      sudo: yes

    - name: Update default conf file
      copy: remote_src=True src=/home/vagrant/checkbox.io/local-conf/default dest=/etc/nginx/sites-available/default
      sudo: yes

    - name: Restart nginx
      service : name=nginx state=reloaded

# Restart mongo
    - name: Restart mongod
      service: name=mongod state=restarted


# Install necessary node modules and start server

    - name: "Check list of Node.js apps running."
      command: forever list
      register: forever_list
      changed_when: false

    - name: "Start example Node.js app."
      command: forever start -o output.log -e error.log  server.js
      args:
        chdir: /home/vagrant/checkbox.io/server-side/site/
      when: "forever_list.stdout.find('/home/vagrant/checkbox.io/server-side/site/server.js') == -1"
